services:
  agentecrewaiwhatsapp:
    image: agentecrewaiwhatsapp
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 crewAI/main.py "]
    ports:
      - 5678:5678
